#!/usr/bin/env python3
"""Generate Mexican Spanish (es-MX) text-to-speech audio for Oye.

Reads app/content/cards.json, collects every non-empty `audio_text`, and makes two
MP3s per sentence with edge-tts (plus, since v1.1, one normal-speed MP3 per scene
dialogue line for the per-line replay buttons; those index entries have no `slow`):
  normal speed  (rate +0%)
  slow          (rate -25%, i.e. about 0.75x, generated by the voice itself so it
                 stays clear instead of being time-stretched)

Files are named by a stable hash of (voice, rate, text), so reruns only create
files for new or changed sentences. Writes app/content/audio.json, the index the
app uses to find each sentence's files.

Usage:  python3 tools/build_audio.py [--prune] [--dry-run]
Needs:  pip install edge-tts   (network access to Microsoft's TTS endpoint)
"""
import argparse, asyncio, hashlib, json, os, sys

APP = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT = os.path.join(APP, 'content')
AUDIO_DIR = os.path.join(APP, 'audio')
INDEX = os.path.join(CONTENT, 'audio.json')

VOICE = 'es-MX-DaliaNeural'
RATES = {'normal': '+0%', 'slow': '-25%'}
CONCURRENCY = 4
RETRIES = 3


def file_name(text, rate):
    h = hashlib.sha1(f'{VOICE}|{rate}|{text}'.encode('utf-8')).hexdigest()[:16]
    return f'{h}.mp3'


def collect_texts():
    with open(os.path.join(CONTENT, 'cards.json'), encoding='utf-8') as f:
        cards = json.load(f)
    texts = []
    for c in cards:
        t = (c.get('audio_text') or '').strip()
        if t and t not in texts:
            texts.append(t)
    # Scene cards play their own audio_text (the relevant lines of the dialogue).
    return texts


def collect_line_texts():
    """v1.1: single dialogue lines for the per-line replay buttons in scene transcripts
    (every line of scenes.json plus each line of a scene card's transcript). Normal speed only."""
    lines = []
    def add(t):
        t = (t or '').strip()
        if t and t not in lines:
            lines.append(t)
    try:
        with open(os.path.join(CONTENT, 'scenes.json'), encoding='utf-8') as f:
            for sc in json.load(f):
                for d in sc.get('dialogue') or []:
                    add(d.get('es'))
    except FileNotFoundError:
        pass
    with open(os.path.join(CONTENT, 'cards.json'), encoding='utf-8') as f:
        for c in json.load(f):
            if c.get('type') == 'scene_question' and c.get('transcript'):
                for part in c['transcript'].split(' / '):
                    add(part.split(': ', 1)[1] if ': ' in part[:26] else part)
    return lines


async def synth(text, rate, path, sem):
    import edge_tts
    async with sem:
        last = None
        for attempt in range(1, RETRIES + 1):
            try:
                tmp = path + '.part'
                await edge_tts.Communicate(text, VOICE, rate=rate).save(tmp)
                if os.path.getsize(tmp) == 0:
                    raise RuntimeError('empty audio')
                os.replace(tmp, path)
                return
            except Exception as e:  # network hiccups: retry
                last = e
                await asyncio.sleep(1.5 * attempt)
        raise RuntimeError(f'failed after {RETRIES} tries: {text!r}: {last}')


async def main_async(args):
    os.makedirs(AUDIO_DIR, exist_ok=True)
    texts = collect_texts()
    index = {'voice': VOICE, 'rates': RATES, 'items': {}}
    todo = []
    for t in texts:
        entry = {}
        for kind, rate in RATES.items():
            name = file_name(t, rate)
            entry[kind] = f'audio/{name}'
            p = os.path.join(AUDIO_DIR, name)
            if not (os.path.exists(p) and os.path.getsize(p) > 0):
                todo.append((t, rate, p))
        index['items'][t] = entry
    n_files = len(texts) * len(RATES)
    lines = [l for l in collect_line_texts() if l not in index['items']]
    for t in lines:
        name = file_name(t, RATES['normal'])
        index['items'][t] = {'normal': f'audio/{name}'}
        p = os.path.join(AUDIO_DIR, name)
        if not (os.path.exists(p) and os.path.getsize(p) > 0):
            todo.append((t, RATES['normal'], p))
    n_files += len(lines)
    print(f'{len(texts)} sentences + {len(lines)} dialogue lines, {n_files} files needed, {len(todo)} to generate (voice {VOICE})')
    if args.dry_run:
        return 0
    sem = asyncio.Semaphore(CONCURRENCY)
    results = await asyncio.gather(*(synth(t, r, p, sem) for t, r, p in todo), return_exceptions=True)
    errors = [r for r in results if isinstance(r, Exception)]
    for e in errors:
        print('ERROR', e, file=sys.stderr)
    if errors:
        return 1
    wanted = {os.path.basename(v) for e in index['items'].values() for v in e.values()}
    stale = [f for f in os.listdir(AUDIO_DIR) if f.endswith('.mp3') and f not in wanted]
    if args.prune:
        for f in stale:
            os.remove(os.path.join(AUDIO_DIR, f))
        print(f'pruned {len(stale)} unused file(s)')
    elif stale:
        print(f'{len(stale)} unused file(s) kept (run with --prune to delete)')
    with open(INDEX, 'w', encoding='utf-8') as f:
        json.dump(index, f, ensure_ascii=False, indent=1)
    print(f'wrote {os.path.relpath(INDEX, APP)}; generated {len(todo)} new file(s)')
    return 0


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--prune', action='store_true', help='delete audio files no card uses any more')
    ap.add_argument('--dry-run', action='store_true')
    sys.exit(asyncio.run(main_async(ap.parse_args())))
